language: node_js
node_js:
  - "node"
  - "lts/*"
addons:
  apt:
    packages:
      - xvfb
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - xvfb-run yarn test --runInBand
branches:
  only:
  - master
cache:
  yarn: true
