#
# https://docs.npmjs.com/trusted-publishers
#

#GIT_COMMITTER_DATE="$(git show master --format=%aD | head -1)" git tag -a "v1.4.6" master -m "release tag v1.4.6" && git push --tags origin master && git --no-pager tag --list --format='%(refname)   %(taggerdate)'

#git tag -d v1.4.6 && git push origin :refs/tags/v1.4.6

name: Publish Package(s)

#on:
#  release:
#    types: [published]

on:
  push:
    #branches: [master]
    tags:
      # https://github.com/daisy/ace/settings/rules
      - "v*" # excludes slash /

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: none
  artifact-metadata: none
  attestations: none
  checks: none
  contents: none # <==========
  deployments: none
  discussions: none
  id-token: none # <==========
  issues: none
  models: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  publish:
    timeout-minutes: 20
    permissions:
      actions: none
      artifact-metadata: none
      attestations: none
      checks: none
      contents: read # <==========
      deployments: none
      discussions: none
      id-token: write # <========== Trusted Publishing OpenID Connect
      issues: none
      models: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    if: "github.event_name != 'pull_request' && github.ref_name == 'master' && github.repository_owner == 'daisy'"
    #if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'release tag')"
    #if: "contains(github.event.head_commit.message, 'release tag')"
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/commits/v6.0.2
      # https://github.com/actions/checkout/commits/de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # https://github.com/actions/checkout/compare/v6.0.2...de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      # https://github.com/actions/setup-node/commits/v6.4.0
      # https://github.com/actions/setup-node/commits/48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      # https://github.com/actions/setup-node/compare/v6.4.0...48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: node --version ; npm --version ; yarn --version
      - run: npm --global install npm@^11
      - run: npm --version
      - run: npm --global install yarn@^1
      - run: yarn --version
      - name: YARN INSTALL and POSTINSTALL(s) (includes BUILD)
        run: rm -rf node_modules ; yarn install --frozen-lockfile --ignore-scripts --network-timeout 1000000 ; cd node_modules/electron ; yarn --verbose --network-timeout 1000000 run postinstall ; cd ../.. ; cd node_modules/puppeteer ; rm -rf ~/.cache/puppeteer/ ; yarn --verbose --network-timeout 1000000 run postinstall ; cd ../.. ; yarn --verbose run postinstall ; ((npm exec --no --offline -- taze --fail-on-outdated --all --force --recursive --include-locked --concurrency 10 --loglevel debug --cwd . && npm exec --no --offline -- taze major --fail-on-outdated --all --force --recursive --include-locked --concurrency 10 --loglevel debug --cwd .) || echo OK)
        shell: bash
        #POSTINSTALL ===> -run: yarn npmVersionsCheck && yarn build && yarn patchElectronJestRunner && yarn patchElectronJestRunner_
      - name: PACKAGE PUBLISH
        #env:
        #  NPM_CONFIG_PROVENANCE: true
        shell: bash
        run: |
          for relativefilepath in packages/*; do
              filename=`basename "${relativefilepath}"`
              echo "${filename} (${relativefilepath})"
              cd "${relativefilepath}"
              if [ "${filename}" != "ace-core-legacy" ]; then
                  echo "PUBLISH: [${filename}] ..."
                  # --dry-run
                  # --provenance

                  #npm publish --access public --tag=next .
                  npm publish --access public --tag=latest

                  # IN CASE OF ERROR THAT INTERRUPTS THE PUBLISHING OF ALL PACKAGES (FOR EXAMPLE: NPM REGISTRY 404), TRY AGAIN AND IGNORE "ALREADY EXIST" ERROR ===>
                  #(npm publish --access public --tag=latest . || echo OK || true)
              fi
              cd - &> /dev/null
          done

#TECHNICAL NOTE: IT IS POSSIBLE TO RETRIVEVE NPM_TOKEN VIA AN OPENIDCONNECT ENDPOINT (DO NOT DO THIS!)
#OIDC_TOKEN=$(curl -sH "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=npm:registry.npmjs.org" | jq -r .value)
#NPM_TOKEN=$(curl -s -X POST https://registry.npmjs.org/-/npm/v1/oidc/token/exchange/package/%40daisy%2Face -H "Content-Type: application/json" -H "Authorization: Bearer $OIDC_TOKEN" -d "{\"oidcToken\":\"$OIDC_TOKEN\"}" | jq -r .token)
#THIS LEAKS THE SECRET IN LOGS: echo $NPM_TOKEN | base64 -w 0 | base64 -w 0
#npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
#npm publish...
